package com.rm.cameraphone.constants;

/**
 * Created by alex
 */
public interface ColorConstants {
    int COLOR_PRIMARY = 0xFF232624;
    int COLOR_PRIMARY_DARK = 0xFF25272a;
    int COLOR_ACCENT = 0xFF007CDB;
    int COLOR_OVERLAY = 0x66000000;

    int COLOR_CAPTURE_CENTER_VIDEO_FILL = 0xFFAD1F39;
    int COLOR_CAPTURE_CENTER_PHOTO_FILL = 0xFF0096FA;
    int COLOR_CAPTURE_CENTER_VIDEO_STROKE = 0xFFB30024;
    int COLOR_RECORD_FILL = 0xFFAD1F39;

    int COLOR_INDICATOR_FILLED = 0xD8FFFFFF;
    int COLOR_INDICATOR_EMPTY = 0x4CFFFFFF;
}
